services:
  db_u:
    # Nombre de tu servicio
    image: mysql:8.0
    container_name: mysql_universidad
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: universidad_db
    ports:
      - "3307:3306"
    volumes:
      # Mapeamos script de la carpeta local a la carpeta de auto-ejecuci√≥n de Docker
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # Esto guarda los datos en PC para que no se borren al apagar Docker
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

    # Ejecutar: docker-compose up -d
